name: superdeck_cli
description: A starting point for Dart libraries or applications.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  yaml: ^3.1.2
  args: ^2.6.0
  path: ^1.9.1
  collection: ^1.19.1
  image: ^4.3.0
  watcher: ^1.1.0
  dart_style: ^2.3.7
  yaml_writer: ^2.0.1
  http: ^1.2.2
  puppeteer: ^3.15.0
  superdeck_core: ^0.0.1
  mason_logger: ^0.3.1
  yaml_edit: ^2.2.1
  markdown: ^7.2.2
  logging: ^1.3.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
