name: superdeck_example
description: An example presentation for SuperDeck

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.0
  mix: ^1.4.5
  superdeck:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  superdeck_cli:
    path: ../../superdeck_cli

flutter:
  uses-material-design: true
  assets:
    - .superdeck/
    - .superdeck/generated/