targets:
  $default:
    builders:
      dart_mappable_builder:
        generate_for:
          - lib/**/*.dart
      mix_generator|spec:
        generate_for:
          - lib/**/*.dart
      mix_generator|dto:
        generate_for:
          - lib/**/*.dart
      mix_generator|enum_utility:
        generate_for:
          - lib/**/*.dart
      mix_generator|class_utility:
        generate_for:
          - lib/**/*.dart
      riverpod_generator:
        generate_for:
          - lib/**/*.dart
      