name: superdeck
description: Presentation slides for Flutter with Flutter
version: 0.0.4
homepage: https://github.com/leoafarias/superdeck

publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  window_manager: ^0.4.3
  collection: ^1.18.0
  path: ^1.9.0
  syntax_highlight: ^0.4.0
  scrollable_positioned_list: ^0.3.8
  pdf: ^3.11.1
  localstorage: ^5.0.0
  go_router: ^14.2.7
  file_picker: ^8.0.7
  path_provider: ^2.1.4
  url_launcher: ^6.3.1
  mix: ^1.5.4
  mix_annotations: ^0.3.1
  flutter_markdown: ^0.7.5
  superdeck_core: ^0.0.1
  markdown: ^7.3.0
  web: ^1.1.0
  file_saver: ^0.2.14
  go_router_paths: ^0.2.2
  image_picker: ^1.1.2
  open_filex: ^4.6.0
  auto_size_text: ^3.0.0
  material_symbols_icons: ^4.2780.0
  uri: ^1.0.0
  webview_flutter: ^4.10.0
  webview_flutter_web: ^0.2.3
  google_fonts: ^6.2.1
  dart_mappable: ^4.3.0
  meta: ^1.15.0
  universal_html: ^2.2.4
  
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mix_generator: ^0.3.2
  custom_lint: ^0.6.8
  # mix_lint: ^0.1.1
  build_runner: ^2.4.13
  dart_mappable_builder: ^4.3.0
  dart_code_metrics_presets: ^2.19.0
  
flutter:
  assets:
    - assets/
    - assets/grammars/