name: superdeck
description: Presentation slides for Flutter with Flutter
version: 0.0.4
homepage: https://github.com/leoafarias/superdeck

publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  window_manager: ^0.3.9
  collection: ^1.18.0
  path: ^1.9.0
  animate_do: ^3.3.4
  syntax_highlight: ^0.4.0
  scrollable_positioned_list: ^0.3.8
  pdf: ^3.11.1
  localstorage: ^5.0.0
  go_router: ^14.1.4
  file_picker: ^8.0.7
  path_provider: ^2.1.4
  url_launcher: ^6.2.6
  mix: ^1.4.4
  mix_annotations: ^0.3.0
  flutter_markdown: ^0.7.3
  superdeck_core: ^0.0.1
  markdown: ^7.2.2
  flutter_hooks: ^0.20.5
  web: ^0.5.1
  file_saver: ^0.2.13
  go_router_paths: ^0.2.2
  flutter_chat_ui: ^1.6.15
  image_picker: ^1.1.2
  open_filex: ^4.5.0
  google_generative_ai: ^0.4.4
  meta: ^1.15.0
  auto_size_text: ^3.0.0
  signals: ^5.4.0
  material_symbols_icons: ^4.2780.0
  get_it: ^7.7.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mix_generator: ^0.2.2
  custom_lint: ^0.6.4
  mix_lint: ^0.1.1
  
  
  
flutter:
  assets:
    - grammars/