targets:
  $default:
    builders:
      dart_mappable_builder:
        generate_for:
          - lib/**/*.dart

global_options:
  dart_mappable_builder:
    options:
      caseStyle: snakeCase
      enumCaseStyle: snakeCase
      discriminatorKey: type
      ignoreNull: true
      generateMethods: [decode, encode, copy, stringify, equals]