name: Test Workflow

on:
  workflow_call:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2

      - name: Install FVM
        shell: bash
        run: |
          curl -fsSL https://fvm.app/install.sh | bash
          fvm use stable --force

      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}

      - name: Setup Melos
        uses: bluefireteam/melos-action@v3

      - uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: false

      - name: Install dependencies
        run: flutter pub get

      - name: Build Runner
        run: melos run gen:build

      - uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: false

      - run: melos run test
